from demo.encoding import content as intro
from demo.dataset import content as dset
from demo.label import content as lenc 
from demo.onehot import content as ohe 
from demo.ordinal import content as oenc
from demo.thermometer import content as thermo
from demo.binary import content as bnry
from demo.baseN import content as base 
from demo.frequency import content as freq 
from demo.target import content as trgt
from demo.kFoldTarget import content as kfold 
from demo.weightOfEvidence import content as woe 
from demo.cyclic import content as cyc